name: Animal Farm NodeJS CI
on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    # needs: build1
    environment: 
      name: demo
    # strategy:
    #   matrix:
    #     envn: ${{fromJSON(needs.env.outputs.matrix)}}
    outputs:
      matrix: ${{ steps.demo.outputs.sample }}
      #matrix2: ${{ steps.demo2.outputs.sample2 }}
    steps:
    - name: Run tests
      run: echo "${{ vars.DEMO }}"
    - name: demo
      id: demo
      run: echo "sample=${{ vars.DEMO }}" >> $GITHUB_OUTPUT



  example_matrix:
    runs-on: ${{ matrix.version }}
    needs: build
    strategy:
      matrix:
        version: ${{fromJSON(needs.build.outputs.matrix)}}
    steps:
    - name: devil
      run: echo "${{fromJSON(needs.build.outputs.matrix)}}"
