name: Expose Configuration Variable
on:
  push:
    branches: 
      - "*" 
jobs:
  expose-variable:
    runs-on: ubuntu-latest
    outputs:
      runnerList: ${{ steps.expose.outputs.runnerList }}
    steps:
      - name: Expose Runner List
        id: expose
        run: echo "runnerList=${{ toJson(env.RUNNER_LIST) }}" >> $GITHUB_ENV
