name: Expose Configuration Variable

on:
  workflow_run:
    workflows: ["Your Main Workflow Name"]
    types:
      - requested

jobs:
  expose-variable:
    runs-on: ubuntu-latest
    outputs:
      osList: ${{ steps.expose.outputs.LIST }}
    steps:
      - name: Expose OS list
        run: echo "::set-output name=osList::${{ github.event.workflow_run.inputs.LIST }}"
