name: Expose Configuration Variable

on:
  workflow_dispatch:

jobs:
  expose-variable:
    runs-on: ubuntu-latest
    outputs:
      runnerList: ${{ steps.expose.outputs.runnerList }}
    steps:
      - name: Expose Runner List
        run: echo "::set-output name=runnerList::${{ toJson(env.RUNNER_LIST) }}"
