name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        target: [Development, Production ]
    uses: ./.github/workflows/demo.yml
    with:
      target-env: ${ { matrix.target } }
    secrets: inherit
    # runs-on: ubuntu-latest
    # outputs:
    # matrix: ${{ steps.envs.outputs.env }}
    # steps:
    # - name: Run tests
    #   run: echo "${{ vars.ENVS }}"
    # - name: demo
    #   id: envs
    #   run: echo "env=${{ vars.envs }}" >> $GITHUB_OUTPUT
