name: Run on Multiple Runners

on:
  workflow_run:
    workflows: ["Expose Configuration Variable"]
    types:
      - completed

jobs:
  my_job:
    runs-on: ${{ fromJson(needs.expose-variable.outputs.runnerList) }}
    needs: expose-variable
    steps:
      - name: Check-out
        uses: actions/checkout@v4
      - name: echo something
        run: echo "Hi"
