name: Simple Workflow

on:
  push:
    branches: [ "*" ]

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        environment: ${{ toJson(fromJson(file('./deployment-config.json.json'))) }}    
    

  build2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environment) }}
        fast-fail: [true]
    steps:
    - name: echo1
      run: echo ${{ matrix.environment }}

    
