# name: Simple Workflow

# on:
#   push:
#     branches: [ "*" ]

# jobs:
#   build1:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v4
#       with:
#         environment: echo "./deployment-config.json"     
    

#   build2:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         environment: ${{ fromJson(inputs.environment) }}
#         fast-fail: [true]
#     steps:
#     - name: echo1
#       run: echo ${{ matrix.environment }}

name: Simple Workflow

on:
  push:
    branches: [ "*" ]

jobs:
  build1:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.read_json.outputs.environment }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Read JSON file and set output
      id: read_json
      run: |
        content=$(<./deployment-config.json)
        echo "::set-output name=environment::${content}"

  build2:
    runs-on: ubuntu-latest
    needs: build1
    strategy:
      matrix:
        environment: ${{fromJson(needs.build1.outputs.environment)}}
        fast-fail: [true]
    steps:
    - name: echo1
      run: echo ${{ matrix.environment }}
