name: Run on Multiple Runners

on:
  workflow_run:
    workflows: ["Expose Configuration Variable"]
    types: 
      - completed

jobs:
  my_job:
    runs-on: ${{ matrix.runner }}
    needs: expose
    strategy:
      matrix:
        runner: ${{fromJson(needs.expose.outputs.runnerList)}}

    steps:
      - name: Check-out
        uses: actions/checkout@v4
      - name: Echo the matrix
        run: echo "${{ matrix.runner }}"
      
      # Add your job steps here
