name: Main Workflow

on:
  push:
    branches: [ "*" ]

jobs:
  set_list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ needs.expose-variable.outputs.osList }}
    steps:
      - name: Use Exposed OS List
        run: echo ${{ matrix.os }}

  my_job:
    needs: set_list
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{fromJson(needs.set_list.outputs.matrix)}}

    steps:
      - name: Check-out
        uses: actions/checkout@v4
      - name: Echo A Var
        run: echo ${{ matrix.os }}
