name: Simple Workflow

on:
  push:
    branches: [ "*" ]

jobs:
  build1:
    environment: env1
    runs-on: ${{ env.RUNNER }}

    steps:
    - name: Step 1
      run: echo "${{ vars.RUNNER }}"

    - name: Step 2
      run: echo "This is step 2"

  build:
    environment: env2
    runs-on: ${{ RUNNER2}}

    steps:
    - name: Step 1
      run: echo "${{ vars.RUNNER2 }}"

    - name: Step 2
      run: echo "This is step 2"

