name: Run on Multiple Runners

on:
  workflow_run:
    workflows: ["Expose Configuration Variable"]
    types:
      - completed
  workflow_dispatch:

jobs:
  dummy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy step."
      - name: Print runnerList
        run: echo "Runner list:${{ needs.expose-variable.outputs.runnerList }}""
  my_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{fromJson(needs.expose-variable.outputs.runnerList)}}

    steps:
      - name: Check-out
        uses: actions/checkout@v4
      - name: echo
        run: echo "${{ matrix.os }}
      
      # Add your job steps here
