name: Simple Workflow

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: echo "This is step 1"

    - name: Step 2
      run: echo "This is step 2"

