name: Run on Multiple Runners

on:
  push:
    branches: [ "*" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: env1
    outputs:
      matrix: ${{ steps.job1.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix="${{vars.RUNNERS}}" 
          echo "$matrix"
          echo "matrix={\"include\":$matrix} >> $GITHUB_OUTPUT"
          echo "${{ steps.job1.outputs.matrix }}"
  # expose-variable:
  #   environment: env1
  #   runs-on: ubuntu-latest
  #   outputs:
  #     runnerList: ${{ steps.expose.outputs.runnerList }}
  #   steps:
  #     - name: Expose Runner List
  #       run: echo "::set-output name=runnerList::${{ toJson(vars.RUNNER_LIST) }}"

  dummy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy step."
      - name: Print runnerList
        run: echo "Runner list:${{ steps.job1.outputs.matrix }}"
  # my_job:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: ${{fromJson(needs.expose-variable.outputs.runnerList)}}

  #   steps:
  #     - name: Check-out
  #       uses: actions/checkout@v4
  #     - name: echo
  #       run: echo "${{ matrix.os }}
      
      # Add your job steps here
