name: Simple Workflow

on:
  push:
    branches: [ "*" ]

jobs:
  build1:
    runs-on: ${{ env.RUNNER }}
    environment: ${{ env.ENVIRONMENT_STAGE }}

    steps:
    - name: Step 1
      run: echo "${{ vars.RUNNER }}"

    - name: Step 2
      run: echo "This is step 2"

