name: Simple Workflow

on:
  push:
    branches: [ "*" ]

env:
  ENV_CONTEXT_VAR: "ubuntu-latest"

jobs:
  build1:
    if: ${{ env.USE_VARIABLES == 'true' }}
    runs-on: ${{ env.RUNNER }}

    steps:
    - name: Step 1
      run: echo "${{ vars.RUNNER }}"

    - name: Step 2
      run: echo "This is step 2"

