name: Simple Workflow

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    environment: env1
    runs-on: '${{ vars.RUNNER }}'

    steps:
    - name: Step 1
      run: echo "This is step 1"

    - name: Step 2
      run: echo "This is step 2"

