name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - "*"
jobs:
  build1:
    runs-on: ubuntu-latest
    environment: demo
    outputs:
      matrix: ${{ steps.envs.outputs.sample }}
    steps:
    - name: Run tests
      run: echo "${{ vars.envs }}"
    - name: environments
      id: envs
      run: echo "sample=${{ vars.ENVS }}" >> $GITHUB_OUTPUT

  build2:
    runs-on: ubuntu-latest
    needs: build1
    environment: ${{ matrix.environment }} 
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{fromJSON(needs.build1.outputs.matrix)}}
      # name: demo, demo2
    # outputs:
    #   matrix: ${{ steps.demo.outputs.sample }}
    steps:
    - name: Run tests
      run: echo "${{ vars.DEMO }}"
    # - name: demo
    #   id: demo
    #   run: echo "sample=${{ vars.DEMO }}" >> $GITHUB_OUTPUT

  # example_matrix:
  #   runs-on: ${{ matrix.version }}
  #   needs: build2
  #   # environment: demo
  #   strategy:
  #     matrix:
  #       version: ${{fromJSON(needs.build2.outputs.matrix)}}
  #   steps:
  #   - name: devil
  #     run: echo "sample"