name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - "*"
jobs:
  # env_build:
  #   runs-on: ubuntu-latest
  #   environment: demo
  #   outputs:
  #     matrix: ${{ steps.demo.outputs.sample }}
  #   steps:
  #   - name: Run tests
  #     run: echo "${{ vars.DEMO }}"
  #   - name: demo
  #     id: demo
  #     run: echo "sample=${{ vars.DEMO }}" >> $GITHUB_OUTPUT

  build2:
    runs-on: ubuntu-latest
    # needs: env_build
    environment: demo
    outputs:
      matrix: ${{ steps.demo.outputs.sample }}
    steps:
    - name: Run tests
      run: echo "${{ vars.DEMO }}"
    - name: demo
      id: demo
      run: echo "sample=${{ vars.DEMO }}" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ${{ matrix.version }}
    needs: build2
    # environment: demo
    strategy:
      matrix:
        version: ${{fromJSON(needs.build2.outputs.matrix)}}
    steps:
    - name: devil
      run: echo "sample"